name: reminder-check

on:
  schedule:
    # Weekdays, 08:00–12:00 SGT (UTC+8) => 00:00–04:00 UTC, hourly
    - cron: "0 0-4 * * 1-5"
  workflow_dispatch: {}   # manual run for testing

permissions:
  issues: write
  pull-requests: write

jobs:
  post-due-reminders:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Find due reminders and comment on issues/PRs
        uses: agrc/reminder-action@v1
